// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVcSOkBLvqSLEnM0Mk__u8Ddl18VMJ7U',
    appId: '1:654229876045:web:bfc726db07bdac881fdb04',
    messagingSenderId: '654229876045',
    projectId: 'dummytwitter-4faa2',
    authDomain: 'dummytwitter-4faa2.firebaseapp.com',
    storageBucket: 'dummytwitter-4faa2.firebasestorage.app',
    measurementId: 'G-L3KCFPFY0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzNiGeuTXO27aHiaC1Ia8zbKgYSydFLZ4',
    appId: '1:654229876045:android:026fb1a5ea57c47c1fdb04',
    messagingSenderId: '654229876045',
    projectId: 'dummytwitter-4faa2',
    storageBucket: 'dummytwitter-4faa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWK2mONcoswqK381wyrjGsVhg3uzCn-t0',
    appId: '1:654229876045:ios:a9dad0ea6245f62b1fdb04',
    messagingSenderId: '654229876045',
    projectId: 'dummytwitter-4faa2',
    storageBucket: 'dummytwitter-4faa2.firebasestorage.app',
    iosBundleId: 'com.example.saveloadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWK2mONcoswqK381wyrjGsVhg3uzCn-t0',
    appId: '1:654229876045:ios:a9dad0ea6245f62b1fdb04',
    messagingSenderId: '654229876045',
    projectId: 'dummytwitter-4faa2',
    storageBucket: 'dummytwitter-4faa2.firebasestorage.app',
    iosBundleId: 'com.example.saveloadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWVcSOkBLvqSLEnM0Mk__u8Ddl18VMJ7U',
    appId: '1:654229876045:web:5aec521f462bb9641fdb04',
    messagingSenderId: '654229876045',
    projectId: 'dummytwitter-4faa2',
    authDomain: 'dummytwitter-4faa2.firebaseapp.com',
    storageBucket: 'dummytwitter-4faa2.firebasestorage.app',
    measurementId: 'G-4C56WH91TQ',
  );
}
